application:
  title: '@project.name@'
  version: '@project.version@'

spring:
  datasource:
    url: <please define>
    driver-class-name: org.postgresql.Driver
    username: <please define>
    password: <please define>
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: when_authorized

openai:
  title: 'Bookshelf API'
  version: 'v0.0.1'
  capacity: 1000
  license:
    name: 'MIT License'
    url:  'https://opensource.org/licenses/MIT'

